spring:
  main:
    banner-mode: off

    #datasource:
    # url: jdbc:mysql://localhost:3306/bankapp
    # hikari:
    #   username: Urmat Bolotbek Uulu
    #   password: **********


    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none

    liquibase:
      change-log: classpath:/db/changelog/changelog-master.xml