server:
  port: 8080
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/carsharing?allowMultiQueries=true
    username: root
    password: 14131103

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/changes/changelog-master.xml
    enabled: true

  springdoc:
    api-docs:
      path: /v3/api-docs
    swagger-ui:
      path: /swagger-ui.html