server:
  port: 8080
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/carsharing?allowMultiQueries=true
    username: root
    password: 14131103
#    hikari:
#      username: root
#      password: 14131103

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  #  sql:
  #    init:
  #      schema-locations:
  #        classpath:db/changelog/changes/v0.0.1-SNAPSHOT/schema.sql
  #      data-locations:
  #        classpath:db/changelog/changes/v0.0.1-SNAPSHOT/data.sql
  #      mode: always

  liquibase:
    change-log: classpath:/db/changelog/changes/changelog-master.xml
    enabled: true