spring:
  main:
    banner-mode: off

  # Конфигурация базы данных
  datasource:
    url: jdbc:mysql://localhost:3306/carsharing
    username: root
    password: 14131103
    hikari:
      username: root
      password: 14131103

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  # Конфигурация инициализации базы данных
  sql:
    init:
      schema-locations:
        classpath:db/schema.sql
      data-locations:
        classpath:db/data.sql
      mode: always

#logging:
#  level:
#    root: INFO

  # Конфигурация базы данных для логгов
  datasource2:
    url: jdbc:mysql://localhost:3306/carsharing_log_db
    username: root
    password: 14131103
    hikari:
      username: root
      password: 14131103
