server:
  port: 8080
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/carsharing?allowMultiQueries=true
    #  ${DATASOURCE_URL}
    username: root
    #  ${DATASOURCE_USERNAME}
    password: 14131103
    #  ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    change-log: classpath:/db/changelog/changes/changelog-master.xml

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

rsa:
  rsa-private-key: classpath:certs\private.pem
  rsa-public-key: classpath:certs\public.pem