spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATASOURCE_URL}
    hikari:
      username: ${DATASOURCE_USERNAME}
      password: ${DATASOURCE_PASSWORD}

  sql:
    init:
      schema-locations:
        classpath:db/schema.sql
      data-locations:
        classpath:db/data.sql
      mode: always

  #logging:
  #    level:
  #      root: DEBUG

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

    #liquibase:
    #change-log: classpath:/db/changelog/changelog-master.xml