spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:mysql://localhost:3306/carsharing  #${DATASOURCE_URL}
    hikari:
      username: root #${DATASOURCE_USERNAME}
      password: 14131103 #${DATASOURCE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      schema-locations:
        classpath:db/schema.sql
      data-locations:
        classpath:db/data.sql
      mode: always

logging:
  level:
    root: INFO

    #liquibase:
    #change-log: classpath:/db/changelog/changelog-master.xml